#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 26 10:58:44 2018

@author: pc
"""

import socket
import json
import time


def receive_msg(client):
    msg = client.recv(2048)
    data = json.loads(msg.decode("utf-8"))
    return data


def make_response_msg(data):
    if data["action"] == "presence":
        response = {
                "action": "probe",
                "time": time.ctime(time.time()),
                "type": "status"
                }
    elif data["action"] == "msg":
        response = {
                "action": "msg",
                "time": time.ctime(time.time()),
                "type": "status"
                }
    else:
        response = {
                "action": "error_msg",
                "time": time.ctime(time.time()),
                "type": "none msg from client"
                }
    return response


def send_msg(client, data):
    msg = json.dumps(data, ensure_ascii=False).encode("utf-8")
    client.send(msg)
    return 0


socket_sv = socket.socket()
socket_sv.bind(('localhost', 8007))
socket_sv.listen(5)

client, addr = socket_sv.accept()
data = receive_msg(client)
response = make_response_msg(data)
send_msg(client, response)
socket_sv.close()
